### ISSUE TITLE
Please don't falsly claim to be an Engineer

### ISSUE THREAD

**Issue by ghost** [Erfan-Ahmadi/circle_collision#4]
@Erfan-Ahmadi You are not an Engineer. 
There ain't such thing as "Rendering Engineer". Engineering is not about sitting behind a screen, and pressing keys on a keyboard to write code. No , engineering is far more serious . Engineering is about designing and building real entities, like turbines or buildings. Software developers have this tendency to make huge and false claims these days. They are not engineers, and will never be engineers, not even close.

**Comment by Erfan-Ahmadi** [comment]
To whomever it is, 
Thanks for letting me know.
I like what I do and I like the people I work with, that's all that matters to me.
I didn't mean to offend you, we may have different definitions of "engineering".
Hope you the best.

**Comment by MMehdiMousavi** [comment]
@ghost please don't falsely claim to be a human being.

**Comment by iOrange** [comment]
@ghost  What if I'm an Electronics Engineer that happens to work as a programmer? Do I still qualify as an Engineer ?

**Comment by JoelLinn** [comment]
Newspaper of the Association of German Engineers:

”Qualified Software-Engineers are essential for the commercial success […]“

https://www.vdi-nachrichten.com/karriere/arbeitsmarkt/software-ingenieure-sind-unerlaesslich-fuer-erfolg/

Good troll though
